[package]
name = "ramify"
description = "Generate annotated branch diagrams from hierarchical data"
readme = "README.md"
version = "0.6.1"
edition = "2024"
authors = ["Alex Rutar <alex@rutar.org>"]
keywords = ["dag", "streaming", "branch"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/alexrutar/ramify"
categories = ["visualization"]

[dev-dependencies]
argh = "0.1"
arrayvec = "0.7.6"
rand = "0.9.2"
rand_distr = "0.5.1"

[[example]]
name = "basic"

[[example]]
name = "cascade"

[[example]]
name = "cascade_merge"

[[example]]
name = "merge"

[[example]]
name = "inverted"

[[example]]
name = "abort"

[[example]]
name = "subset"

[[example]]
name = "tree_error"

[[example]]
name = "numbered"

[[example]]
name = "gallery"
