//! # Branch diagram writers
//!
//! This module contains the [`DiagramWrite`] trait, which is an abstraction over types which can
//! write the components of a branch diagram. Internally, a [`Generator`](crate::Generator) emits
//! calls to the [`DiagramWrite`] methods in order to draw the diagram.
//!
//! ## Provided implementations
//!
//! In most cases, you do not need to implement [`DiagramWrite`] yourself. There are two provided
//! diagram writers: an [`IOWriter`] which holds an [`io::Write`] implementation, and a
//! [`FmtWriter`] which holds a [`fmt::Write`] implementation.
//!
//! The appearance of the diagram generated by these writers is specified by the [`Style`] struct.
mod branch;
mod shim;

pub use self::branch::{Branch, MergeBranch};
use shim::{Shim, WriteInner};

use std::{fmt, io};

/// Types which know how to write branch diagrams.
///
/// A branch diagram is built-up sequentially by a sequence of calls to methods in this trait.
/// Usually, you don't need to implement this trait yourself and you can use an [`IOWriter`] or
/// [`FmtWriter`].
///
/// This trait is designed to minimize the amount of state that an implementation needs to hold.
/// Therefore, most of the methods are passed various column counts used to provide extra context
/// of the situation.
pub trait DiagramWrite {
    /// An error which may occur while writing.
    type Error;

    /// Write a [branch](Branch).
    ///
    /// - `start` is the number of columns which have already been written
    /// - `skip` is the number of empty columns which precede the branch which the writer should
    ///   fill
    ///
    /// # Example
    /// If `start = 4`, `skip = 1`, and `branch = Branch::ShiftForkLeft(1, 1)`, the
    /// writer is expected to emit the following characters:
    /// ```txt
    ///
    /// ++++ ╭┬─╯
    ///      ↑↑↑↑ The branch to write
    ///     ↑ Column fill character
    /// ↑↑↑↑ Already written
    /// ```
    fn write_branch(
        &mut self,
        start: usize,
        skip: usize,
        branch: Branch,
    ) -> Result<(), Self::Error>;

    /// Write a [merge branch](MergeBranch).
    ///
    /// - `start` is the number of columns which have already been written
    /// - `skip` is the number of empty columns which precede the branch which the writer should
    ///   fill
    ///
    /// # Example
    /// If `start = 3`, `skip = 2`, and `branch = MergeBranch::Join`, the
    /// writer is expected to emit the following characters:
    /// ```txt
    ///
    /// +++──┴
    ///      ↑ The branch to write
    ///    ↑↑ Merge fill characters
    /// ↑↑↑ Already written
    /// ```
    fn write_merge_branch(
        &mut self,
        start: usize,
        skip: usize,
        merge: MergeBranch,
    ) -> Result<(), Self::Error>;

    /// Prepare to write an annotation line.
    ///
    /// Implementors should use this to write alignment characters and other text which precedes
    /// the annotation line itself.
    ///
    /// - `idx` is the index of the annotation line in the block of annotations
    /// - `written` is the number of columns that were written in this line
    /// - `required` is the total number of columns that the diagram requires to fit future writes
    ///
    /// It is guaranteed that `required >= written`. If an annotation occupies multiple lines,
    /// `required` will be constant across all of the lines in the annotation, and in many cases
    /// will be exactly equal to the maximum value of `written`.
    ///
    /// # Example
    /// In the below example, when writing Line 0, `written = 1` and `required = 3`, whereas in
    /// Line 1 and Line 2, `written = 3` and `required = 3`. In Line 4, `written = 2` and `required
    /// = 2` since there are no subsequent lines.
    /// ```txt
    /// 0  < Line 0
    /// ├┬╮< Line 1
    /// │││< Line 3
    /// │1│
    /// 2╭╯
    ///  3< Line 4
    /// ```
    fn prepare_annotation(
        &mut self,
        idx: usize,
        written: usize,
        required: usize,
    ) -> Result<(), Self::Error>;

    /// Write the text of the annotation line.
    fn write_annotation(&mut self, line: &str) -> Result<(), Self::Error>;

    /// Write a newline.
    ///
    /// This is called to terminate branch diagram lines which do not contain annotations.
    fn write_newline(&mut self) -> Result<(), Self::Error>;

    /// Prepare and then write an annotation followed by a newline.
    ///
    /// The default implementation calls, in order,
    ///
    /// 1. [`prepare_annotation`](DiagramWrite::prepare_annotation),
    /// 2. [`write_annotation`](DiagramWrite::write_annotation)
    /// 3. [`write_newline`](DiagramWrite::write_newline).
    fn write_annotation_line(
        &mut self,
        idx: usize,
        written: usize,
        required: usize,
        line: &str,
    ) -> Result<(), Self::Error> {
        self.prepare_annotation(idx, written, required)?;
        self.write_annotation(line)?;
        self.write_newline()
    }
}

/// A diagram writer which writes into an [`io::Write`] implementation.
///
/// Also see the [`Style::io_writer`] method.
pub struct IOWriter<W> {
    /// The style.
    style: Style,
    /// The writer.
    writer: W,
}

impl<W> IOWriter<W> {
    /// Construct a new diagram writer with the provided style and internal [`io::Write`]
    /// implementation.
    pub fn new(style: Style, writer: W) -> Self {
        Self { style, writer }
    }

    /// Recover the style and the internal writer.
    pub fn components(self) -> (Style, W) {
        (self.style, self.writer)
    }
}

impl<W: io::Write> WriteInner for IOWriter<W> {
    type Error = io::Error;

    #[inline]
    fn write_char(&mut self, ch: char) -> io::Result<()> {
        self.writer
            .write_all(ch.encode_utf8(&mut [0; 4]).as_bytes())
    }

    #[inline]
    fn write_gutter(&mut self) -> io::Result<()> {
        let mut buf = [0; 4];
        let gutter_bytes = self
            .style
            .charset
            .horizontal
            .encode_utf8(&mut buf)
            .as_bytes();
        for _ in 0..self.style.gutter_width {
            self.writer.write_all(gutter_bytes)?;
        }
        Ok(())
    }

    #[inline]
    fn style(&self) -> &Style {
        &self.style
    }

    #[inline]
    fn write_annotation(&mut self, line: &str) -> io::Result<()> {
        self.writer.write_all(line.as_bytes())
    }

    #[inline]
    fn write_newline(&mut self) -> io::Result<()> {
        self.writer.write_all(b"\n")
    }
}

impl<W: io::Write> DiagramWrite for IOWriter<W> {
    type Error = io::Error;

    #[inline]
    fn write_branch(
        &mut self,
        start: usize,
        skip: usize,
        branch: Branch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_branch(start, skip, branch)
    }

    #[inline]
    fn write_merge_branch(
        &mut self,
        start: usize,
        skip: usize,
        merge: MergeBranch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_merge_branch(start, skip, merge)
    }

    #[inline]
    fn prepare_annotation(
        &mut self,
        _idx: usize,
        written: usize,
        required: usize,
    ) -> Result<(), Self::Error> {
        Shim(self).prepare_annotation(written, required)
    }

    #[inline]
    fn write_annotation(&mut self, line: &str) -> Result<(), Self::Error> {
        Shim(self).write_annotation(line)
    }

    #[inline]
    fn write_newline(&mut self) -> Result<(), Self::Error> {
        Shim(self).write_newline()
    }
}

/// A diagram writer which writes into an [`io::Write`] implementation.
pub struct FmtWriter<W> {
    /// The style.
    style: Style,
    /// The writer.
    writer: W,
}

impl<W> FmtWriter<W> {
    /// Construct a new diagram writer with the provided style and internal [`fmt::Write`]
    /// implementation.
    ///
    /// Also see the [`Style::fmt_writer`] method.
    pub fn new(style: Style, writer: W) -> Self {
        Self { style, writer }
    }

    /// Recover the style and the internal writer.
    pub fn components(self) -> (Style, W) {
        (self.style, self.writer)
    }
}

impl<W: fmt::Write> WriteInner for FmtWriter<W> {
    type Error = fmt::Error;

    #[inline]
    fn write_char(&mut self, ch: char) -> fmt::Result {
        self.writer.write_char(ch)
    }

    #[inline]
    fn write_gutter(&mut self) -> fmt::Result {
        for _ in 0..self.style.gutter_width {
            self.writer.write_char(self.style.charset.horizontal)?;
        }
        Ok(())
    }

    #[inline]
    fn style(&self) -> &Style {
        &self.style
    }

    #[inline]
    fn write_annotation(&mut self, line: &str) -> fmt::Result {
        self.writer.write_str(line)
    }

    #[inline]
    fn write_newline(&mut self) -> fmt::Result {
        self.writer.write_char('\n')
    }
}

impl<W: fmt::Write> DiagramWrite for FmtWriter<W> {
    type Error = fmt::Error;

    #[inline]
    fn write_branch(
        &mut self,
        start: usize,
        skip: usize,
        branch: Branch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_branch(start, skip, branch)
    }

    #[inline]
    fn write_merge_branch(
        &mut self,
        start: usize,
        skip: usize,
        merge: MergeBranch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_merge_branch(start, skip, merge)
    }

    #[inline]
    fn prepare_annotation(
        &mut self,
        _idx: usize,
        written: usize,
        required: usize,
    ) -> Result<(), Self::Error> {
        Shim(self).prepare_annotation(written, required)
    }

    #[inline]
    fn write_annotation(&mut self, line: &str) -> Result<(), Self::Error> {
        Shim(self).write_annotation(line)
    }

    #[inline]
    fn write_newline(&mut self) -> Result<(), Self::Error> {
        Shim(self).write_newline()
    }
}

/// Configuration for the appearance of the branch diagram.
///
/// This struct is used by the [`IOWriter`] and [`FmtWriter`] implementations of [`DiagramWrite`].
/// For more fine-grained configuration, one should manually implement [`DiagramWrite`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Style {
    /// The set of characters to use in the diagram.
    charset: Charset,
    /// The margin at the beginning of each annotation.
    annotation_margin: usize,
    /// The minimum left alignment of each annotation line.
    annotation_justification: usize,
    /// The gap between vertices.
    gutter_width: usize,
    /// Put merge lines on top.
    merge_over: bool,
}

impl Style {
    /// Initialize a new style from the provided character set.
    pub const fn new(charset: Charset) -> Self {
        Self {
            charset,
            annotation_margin: 1,
            annotation_justification: 0,
            gutter_width: 0,
            merge_over: false,
        }
    }

    /// Get an [`IOWriter`] wrapping the provided writer using this style.
    pub const fn io_writer<W>(self, writer: W) -> IOWriter<W> {
        IOWriter {
            style: self,
            writer,
        }
    }

    /// Get a [`FmtWriter`] wrapping the provided writer using this style.
    pub const fn fmt_writer<W>(self, writer: W) -> FmtWriter<W> {
        FmtWriter {
            style: self,
            writer,
        }
    }

    /// Initialize with the [rounded corners](Charset::rounded_corners) character set.
    ///
    /// The charset looks as follows.
    /// ```txt
    /// 0    
    /// ├┬╮  
    /// │1├╮
    /// ││2│
    /// │3│├╮
    /// │╭╯││
    /// ││╭┤│
    /// │││4│
    /// ││5╭╯
    /// │6╭╯
    /// 7╭╯  
    ///  8   
    /// ```
    pub const fn rounded_corners() -> Self {
        Self::new(Charset::rounded_corners())
    }

    /// Initialize with the [sharp corners](Charset::sharp_corners) character set.
    ///
    /// The charset looks as follows.
    /// ```txt
    /// 0
    /// ├┬┐
    /// │1├┐
    /// ││2│
    /// │3│├┐
    /// │┌┘││
    /// ││┌┤│
    /// │││4│
    /// ││5┌┘
    /// │6┌┘
    /// 7┌┘
    ///  8
    /// ```
    pub const fn sharp_corners() -> Self {
        Self::new(Charset::sharp_corners())
    }

    /// Initialize with the [doubled lines](Charset::doubled_lines) character set.
    ///
    /// The charset looks as follows.
    /// ```txt
    /// 0
    /// ╠╦╗
    /// ║1╠╗
    /// ║║2║
    /// ║3║╠╗
    /// ║╔╝║║
    /// ║║╔╣║
    /// ║║║4║
    /// ║║5╔╝
    /// ║6╔╝
    /// 7╔╝
    ///  8
    /// ```
    pub const fn doubled_lines() -> Self {
        Self::new(Charset::doubled_lines())
    }

    /// Reset the character set used in the style.
    pub const fn charset(mut self, charset: Charset) -> Self {
        self.charset = charset;
        self
    }

    /// Invert the internal character set.
    ///
    /// This inverts vertically by swapping characters like `╯` and `╮`. Calling this method twice
    /// will return the original character set. This makes the lines connect correctly when writing
    /// the diagram lines in reverse order.
    ///
    /// Also see [`Config::inverted_annotations`](crate::Config::inverted_annotations) to modify the layout algorithm to
    /// draw annotations correctly if you are also rendering annotations.
    ///
    /// ## Example
    /// Inverting has the following effect (the third column has reversed lines).
    /// ```txt
    /// 0         0          8
    /// ├┬╮       ├┴╯       7╰╮
    /// │1├╮      │1├╯      │6╰╮
    /// ││2│      ││2│      ││5╰╮
    /// │3│├╮     │3│├╯     │││4│
    /// │╭╯││  →  │╰╮││  ↺  ││╰┤│
    /// ││╭┤│     ││╰┤│     │╰╮││
    /// │││4│  →  │││4│  ↺  │3│├╯
    /// ││5╭╯     ││5╰╮     ││2│
    /// │6╭╯      │6╰╮      │1├╯
    /// 7╭╯       7╰╮       ├┴╯
    ///  8         8        0
    /// ```
    pub const fn invert(mut self) -> Self {
        self.charset = self.charset.invert();
        self
    }

    /// The margin at the beginning of each annotation.
    ///
    /// This is the number of characters written at the beginning of the annotation line to create
    /// a gap between the annotation and the branch diagram lines.
    ///
    /// The default value is `1`.
    ///
    /// ## Example
    /// Here is an example going from annotation margin `0` to `2`.
    /// ```txt
    /// 0             0
    /// ├┬╮           ├┬╮
    /// │1├╮L0    →   │1├╮  L0
    /// ││││L1        ││││  L1
    /// ││2│          ││2│
    /// │3│├╮L0   →   │3│├╮  L0
    /// │╭╯││         │╭╯││
    /// ││╭┤│         ││╭┤│
    /// │││4│L0   →   │││4│  L0
    /// │││╭╯L1       │││╭╯  L1
    /// ││││ L2       ││││   L2
    /// ││5│          ││5│
    /// │6╭╯          │6╭╯
    /// 7╭╯           7╭╯
    ///  8             8
    /// ```
    pub const fn annotation_margin(mut self, annotation_margin: usize) -> Self {
        self.annotation_margin = annotation_margin;
        self
    }

    /// The minimum left justification of the annotations.
    ///
    /// Annotation lines will never begin earlier than this value, but may begin later than this
    /// value if the row width plus annotation margin exceeds the justification.
    ///
    /// The default value is `0`.
    pub const fn annotation_justification(mut self, annotation_justification: usize) -> Self {
        self.annotation_justification = annotation_justification;
        self
    }

    /// The gap between columns in the branch diagram.
    ///
    /// The default value is `0`.
    ///
    /// ## Example
    /// Setting the gutter width to `1` has the following effect.
    /// ```txt
    /// 0         0     
    /// ├┬╮       ├─┬─╮  
    /// │1├╮      │ 1 ├─╮
    /// ││2│      │ │ 2 │
    /// │3│├╮     │ 3 │ ├─╮
    /// │╭╯││  →  │ ╭─╯ │ │
    /// ││╭┤│     │ │ ╭─┤ │
    /// │││4│  →  │ │ │ 4 │
    /// ││5╭╯     │ │ 5 ╭─╯
    /// │6╭╯      │ 6 ╭─╯
    /// 7╭╯       7 ╭─╯   
    ///  8          8
    ///            ^ ^ ^ ^ gutters
    /// ```
    pub const fn gutter_width(mut self, gutter_width: usize) -> Self {
        self.gutter_width = gutter_width;
        self
    }

    /// Whether merge lines should go above diagram lines.
    ///
    /// Setting this value to `true` typically requires a
    /// [gutter width](Self::gutter_width) of at least 1 for diagram clarity.
    ///
    /// The default value is `false`.
    ///
    /// ## Example
    /// With a gutter width of 1, setting this to `true` has the following effect:
    /// ```txt
    /// 0             0
    /// ├─╮           ├─╮
    /// │ 1           │ 1
    /// │ ├─╮         │ ├─╮
    /// │ 2 ╰───╮     │ 2 ╰───╮
    /// │ ├─┬─╮ │     │ ├─┬─╮ │
    /// ├─│─╯ │ │  →  ├───╯ │ │
    /// 3 │ ╭─╯ │     3 │ ╭─╯ │
    /// │ │ 4 ╭─╯     │ │ 4 ╭─╯
    /// │ ╰─╮ │       │ ╰─╮ │
    /// ├─╮ │ │       ├─╮ │ │
    /// ├─│─╯ │    →  ├───╯ │
    /// 5 │ ╭─╯       5 │ ╭─╯
    /// ╭─┴─╯         ╭─┴─╯
    /// 6             6
    /// ```
    pub const fn merge_over(mut self, merge_over: bool) -> Self {
        self.merge_over = merge_over;
        self
    }
}

/// The set of characters to use in the diagram.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Charset {
    /// The ` ` character.
    pub space: char,
    /// The `╮` character.
    pub down_and_left: char,
    /// The `╭` character.
    pub down_and_right: char,
    /// The `╯` character.
    pub up_and_left: char,
    /// The `╰` character.
    pub up_and_right: char,
    /// The `─` character.
    pub horizontal: char,
    /// The `│` character.
    pub vertical: char,
    /// The `┬` character.
    pub down_and_horizontal: char,
    /// The `┴` character.
    pub up_and_horizontal: char,
    /// The `┤` character.╮
    pub vertical_and_left: char,
    /// The `├` character.
    pub vertical_and_right: char,
    /// The `┼` character.
    pub vertical_and_horizontal: char,
}

impl Charset {
    /// Using this character set in a diagram style.
    pub const fn style(self) -> Style {
        Style::new(self)
    }

    /// The rounded corners character set.
    /// ```txt
    /// ╯ ┴ ╰
    /// ┤ ┼ ├ ─
    /// ╮ ┬ ╭ │
    /// ```
    pub const fn rounded_corners() -> Self {
        Self {
            space: ' ',
            down_and_left: '╮',
            down_and_right: '╭',
            up_and_left: '╯',
            up_and_right: '╰',
            horizontal: '─',
            vertical: '│',
            down_and_horizontal: '┬',
            up_and_horizontal: '┴',
            vertical_and_left: '┤',
            vertical_and_right: '├',
            vertical_and_horizontal: '┼',
        }
    }

    /// The sharp corners character set.
    /// ```txt
    /// ┘ ┴ └
    /// ┤ ┼ ├ ─
    /// ┐ ┬ ┌ │
    /// ```
    pub const fn sharp_corners() -> Self {
        Self {
            down_and_left: '┐',
            down_and_right: '┌',
            up_and_left: '┘',
            up_and_right: '└',
            ..Self::rounded_corners()
        }
    }

    /// The doubled lines character set.
    /// ```txt
    /// ╝ ╩ ╚
    /// ╣ ╬ ╠ ═
    /// ╗ ╦ ╔ ║
    /// ```
    pub const fn doubled_lines() -> Self {
        Self {
            space: ' ',
            down_and_left: '╗',
            down_and_right: '╔',
            up_and_left: '╝',
            up_and_right: '╚',
            horizontal: '═',
            vertical: '║',
            down_and_horizontal: '╦',
            up_and_horizontal: '╩',
            vertical_and_left: '╣',
            vertical_and_right: '╠',
            vertical_and_horizontal: '╬',
        }
    }

    /// Flip the orientation of the charset vertically.
    ///
    /// This swaps the `down_*` characters with the `up_*` characters. This is useful when you
    /// want to render the branch diagram with the root at the bottom since
    /// it will make the branch diagram lines connect correctly when the lines are written in
    /// reverse order.
    ///
    /// Also see [`Config::inverted_annotations`](crate::Config::inverted_annotations) to modify the layout algorithm to
    /// draw annotations correctly.
    pub const fn invert(self) -> Self {
        Self {
            down_and_left: self.up_and_left,
            down_and_right: self.up_and_right,
            down_and_horizontal: self.up_and_horizontal,
            up_and_left: self.down_and_left,
            up_and_right: self.down_and_right,
            up_and_horizontal: self.down_and_horizontal,
            ..self
        }
    }
}
