//! # Branch diagram writers
//!
//! This module contains the [`DiagramWrite`] trait, which is an abstraction over types which can
//! write the components of a branch diagram. Internally, a [`Generator`](crate::Generator) emits
//! calls to the [`DiagramWrite`] methods in order to draw the diagram.
//!
//! In most cases, you do not need to implement [`DiagramWrite`] yourself. There are two provided
//! diagram writers: an [`IOWriter`] which holds an [`io::Write`] implementation, and a
//! [`FmtWriter`] which holds a [`fmt::Write`] implementation.
//! The appearance of the diagram generated by these writers is specified by the [`Style`] struct.
//!
//! Note that layout configuration is found in the [`Config`](crate::Config) struct. Essentially,
//! configuration which results in a different sequence of calls to the [`DiagramWrite`]
//! methods belongs in [`Config`](crate::Config).
//!
//! ## Composing diagram writers
//!
//! If you want to customize the diagram writer, in many simple cases it is also possible to wrap an
//! internal diagram writer. The [`DiagramWrite::write_fmt`] helps to compose writers, and also
//! can make it simpler to write code which is generic over an arbitrary diagram writer.
//!
//! ### Numbered annotation lines
//! In the following example, we wrap a diagram writer to print line numbers before each annotation
//! line.
//!
//! Try this out with `cargo run --example numbered`.
//! ```
//! use ramify::writer::{Branch, DiagramWrite, IOWriter, MergeBranch};
//!
//! struct NumberedAnnotationWriter<W> {
//!     inner: W,
//! }
//!
//! impl<W: DiagramWrite> DiagramWrite for NumberedAnnotationWriter<W> {
//!     type Error = W::Error;
//!
//!     fn write_fmt(&mut self, args: std::fmt::Arguments<'_>) -> Result<(), Self::Error> {
//!         self.inner.write_fmt(args)
//!     }
//!
//!     fn write_branch(
//!         &mut self,
//!         start: usize,
//!         skip: usize,
//!         branch: Branch,
//!     ) -> Result<(), Self::Error> {
//!         self.inner.write_branch(start, skip, branch)
//!     }
//!
//!     fn write_merge_branch(
//!         &mut self,
//!         start: usize,
//!         skip: usize,
//!         merge: MergeBranch,
//!     ) -> Result<(), Self::Error> {
//!         self.inner.write_merge_branch(start, skip, merge)
//!     }
//!
//!     fn prepare_annotation(
//!         &mut self,
//!         idx: usize,
//!         written: usize,
//!         required: usize,
//!     ) -> Result<(), Self::Error> {
//!         self.inner.prepare_annotation(idx, written, required)
//!     }
//!
//!     fn write_annotation(&mut self, idx: usize, line: &str) -> Result<(), Self::Error> {
//!         // write the line number followed by the line
//!         write!(self.inner, "{}. {line}", idx + 1)
//!     }
//!
//!     fn write_newline(&mut self) -> Result<(), Self::Error> {
//!         self.inner.write_newline()
//!     }
//! }
//! ```
//!
//! ### Logging diagram write calls
//! In the following example, we also log the write calls before passing them to the writer.
//!
//! Try this out with `cargo run --example log_writes`.
//! ```
//! use ramify::writer::{Branch, DiagramWrite, MergeBranch};
//!
//! struct LoggingWriter<W> {
//!     calls: Vec<Instruction>,
//!     writer: W,
//! }
//!
//! enum Instruction {
//!     WriteBranch(usize, usize, Branch),
//!     WriteMergeBranch(usize, usize, MergeBranch),
//!     PrepareAnnotation(usize, usize, usize),
//!     WriteAnnotation(usize, String),
//!     WriteNewline,
//! }
//!
//! impl<W: DiagramWrite> DiagramWrite for LoggingWriter<W> {
//!     type Error = W::Error;
//!
//!     fn write_fmt(&mut self, args: std::fmt::Arguments<'_>) -> Result<(), Self::Error> {
//!         // don't log a fmt call since this is not emitted by a Generator anyway
//!         self.writer.write_fmt(args)
//!     }
//!
//!     fn write_branch(
//!         &mut self,
//!         start: usize,
//!         skip: usize,
//!         branch: Branch,
//!     ) -> Result<(), Self::Error> {
//!         self.calls
//!             .push(Instruction::WriteBranch(start, skip, branch));
//!         self.writer.write_branch(start, skip, branch)
//!     }
//!
//!     fn write_merge_branch(
//!         &mut self,
//!         start: usize,
//!         skip: usize,
//!         merge: MergeBranch,
//!     ) -> Result<(), Self::Error> {
//!         self.calls
//!             .push(Instruction::WriteMergeBranch(start, skip, merge));
//!         self.writer.write_merge_branch(start, skip, merge)
//!     }
//!
//!     fn prepare_annotation(
//!         &mut self,
//!         idx: usize,
//!         written: usize,
//!         required: usize,
//!     ) -> Result<(), Self::Error> {
//!         self.calls
//!             .push(Instruction::PrepareAnnotation(idx, written, required));
//!         self.writer.prepare_annotation(idx, written, required)
//!     }
//!
//!     fn write_annotation(&mut self, idx: usize, line: &str) -> Result<(), Self::Error> {
//!         self.calls
//!             .push(Instruction::WriteAnnotation(idx, line.to_owned()));
//!         self.writer.write_annotation(idx, line)
//!     }
//!
//!     fn write_newline(&mut self) -> Result<(), Self::Error> {
//!         self.calls.push(Instruction::WriteNewline);
//!         self.writer.write_newline()
//!     }
//! }
//! ```

mod branch;
mod shim;
mod style;

pub use self::{
    branch::{Branch, MergeBranch},
    style::{Charset, Style},
};
use shim::{Shim, WriteInner};

use std::{fmt, io};

/// Types which know how to write branch diagrams.
///
/// A branch diagram is built-up sequentially by a sequence of calls to methods in this trait.
/// Usually, you don't need to implement this trait yourself and you can use an [`IOWriter`] or
/// [`FmtWriter`].
///
/// This trait is designed to minimize the amount of state that an implementation needs to hold.
/// Many of the methods are passed various column counts to provide the context in which the write occurs.
///
/// See the [module-level documentation](crate::writer) for more detail and examples.
pub trait DiagramWrite {
    /// An error which may occur while writing.
    type Error;

    /// A glue method to make it easier to compose diagram writers.
    ///
    /// In particular, this allows writing into a diagram writer with the [`write!`] macro.
    /// Calls to this method are never generated by a [`Generator`](crate::Generator). However,
    /// consumers of this trait may find it convenient for writing code which is generic over
    /// diagram writers.
    fn write_fmt(&mut self, args: fmt::Arguments<'_>) -> Result<(), Self::Error>;

    /// Write a [branch](Branch).
    ///
    /// - `start` is the number of columns which have already been written
    /// - `skip` is the number of empty columns which precede the branch which the writer should
    ///   fill
    ///
    /// # Example
    /// If `start = 4`, `skip = 1`, and `branch = Branch::ShiftForkLeft(1, 1)`, the
    /// writer is expected to emit the following characters:
    /// ```txt
    ///
    /// ++++ ╭┬─╯
    ///      ↑↑↑↑ The branch to write
    ///     ↑ Column fill character
    /// ↑↑↑↑ Already written
    /// ```
    fn write_branch(
        &mut self,
        start: usize,
        skip: usize,
        branch: Branch,
    ) -> Result<(), Self::Error>;

    /// Write a [merge branch](MergeBranch).
    ///
    /// - `start` is the number of columns which have already been written
    /// - `skip` is the number of empty columns which precede the branch which the writer should
    ///   fill
    ///
    /// # Example
    /// If `start = 3`, `skip = 2`, and `branch = MergeBranch::Join`, the
    /// writer is expected to emit the following characters:
    /// ```txt
    ///
    /// +++──┴
    ///      ↑ The branch to write
    ///    ↑↑ Merge fill characters
    /// ↑↑↑ Already written
    /// ```
    fn write_merge_branch(
        &mut self,
        start: usize,
        skip: usize,
        merge: MergeBranch,
    ) -> Result<(), Self::Error>;

    /// Prepare to write an annotation line.
    ///
    /// Implementors should use this to write alignment characters and other text which precedes
    /// the annotation line itself.
    ///
    /// - `idx` is the index of the annotation line in the block of annotations
    /// - `written` is the number of columns that were written in this line
    /// - `required` is the total number of columns that the diagram requires to fit future writes
    ///
    /// It is guaranteed that `required >= written`. If an annotation occupies multiple lines,
    /// `required` will be constant across all of the lines in the annotation, and in many cases
    /// will be exactly equal to the maximum value of `written`.
    ///
    /// # Example
    /// In the below example, when writing Line 0, `written = 1` and `required = 3`, whereas in
    /// Line 1 and Line 2, `written = 3` and `required = 3`. In Line 3, `written = 2` and `required
    /// = 2` since there are no subsequent lines which will occupy more space.
    /// ```txt
    /// 0  < Line 0
    /// ├┬╮< Line 1
    /// │││< Line 2
    /// │1│
    /// 2╭╯
    ///  3< Line 3
    /// ```
    fn prepare_annotation(
        &mut self,
        idx: usize,
        written: usize,
        required: usize,
    ) -> Result<(), Self::Error>;

    /// Write the text of a single annotation line.
    ///
    /// The index `idx` is the index of the annotation line in the block of annotations.
    fn write_annotation(&mut self, idx: usize, line: &str) -> Result<(), Self::Error>;

    /// Write a newline.
    ///
    /// This is called when the diagram row is completed.
    fn write_newline(&mut self) -> Result<(), Self::Error>;
}

impl<W: DiagramWrite + ?Sized> DiagramWrite for &mut W {
    type Error = W::Error;

    #[inline]
    fn write_fmt(&mut self, args: fmt::Arguments<'_>) -> Result<(), Self::Error> {
        (**self).write_fmt(args)
    }

    #[inline]
    fn write_branch(
        &mut self,
        start: usize,
        skip: usize,
        branch: Branch,
    ) -> Result<(), Self::Error> {
        (**self).write_branch(start, skip, branch)
    }

    #[inline]
    fn write_merge_branch(
        &mut self,
        start: usize,
        skip: usize,
        merge: MergeBranch,
    ) -> Result<(), Self::Error> {
        (**self).write_merge_branch(start, skip, merge)
    }

    #[inline]
    fn prepare_annotation(
        &mut self,
        idx: usize,
        written: usize,
        required: usize,
    ) -> Result<(), Self::Error> {
        (**self).prepare_annotation(idx, written, required)
    }

    #[inline]
    fn write_annotation(&mut self, idx: usize, line: &str) -> Result<(), Self::Error> {
        (**self).write_annotation(idx, line)
    }

    #[inline]
    fn write_newline(&mut self) -> Result<(), Self::Error> {
        (**self).write_newline()
    }
}

/// A diagram writer which writes into an [`io::Write`] implementation.
///
/// Note that this writer provides *no additional buffering*, and a diagram writer emits a very large number of
/// small writes to the internal writer. It is strongly recommended to provide a buffered writer,
/// for example with a [`BufWriter`](io::BufWriter) or a [`LineWriter`](io::LineWriter). Some
/// built-in writers, such as [standard output](io::stdout), are automatically line buffered.
///
/// The [`DiagramWrite`] implementation will never flush output. Since a newline is always written
/// after every diagram row, it is not necessary to flush if you are using a line-buffered writer.
pub struct IOWriter<W> {
    /// The style.
    style: Style,
    /// The writer.
    writer: W,
}

impl<W> IOWriter<W> {
    /// Construct a new diagram writer with the provided style and internal [`io::Write`]
    /// implementation.
    ///
    /// Also see the [`Style::io_writer`] method.
    #[inline]
    pub const fn new(style: Style, writer: W) -> Self
    where
        W: io::Write,
    {
        Self { style, writer }
    }

    /// Get a mutable reference to the internal writer.
    ///
    /// Note that this struct automatically implements [`io::Write`] by passing writes to
    /// the internal writer.
    #[inline]
    pub const fn writer(&mut self) -> &mut W {
        &mut self.writer
    }

    /// Get a reference to the internal style.
    ///
    /// If you must modify the style, first decompose into [components](Self::components) and then rebuild
    /// this struct.
    #[inline]
    pub const fn style(&self) -> &Style {
        &self.style
    }

    /// Recover the style and the internal writer.
    #[inline]
    pub fn components(self) -> (Style, W) {
        (self.style, self.writer)
    }
}

impl<W: io::Write> WriteInner for IOWriter<W> {
    type Error = io::Error;

    #[inline]
    fn write_fmt(&mut self, args: std::fmt::Arguments<'_>) -> Result<(), Self::Error> {
        self.writer.write_fmt(args)
    }

    #[inline]
    fn write_char(&mut self, ch: char) -> io::Result<()> {
        self.writer
            .write_all(ch.encode_utf8(&mut [0; 4]).as_bytes())
    }

    #[inline]
    fn write_gutter(&mut self) -> io::Result<()> {
        let mut buf = [0; 4];
        let gutter_bytes = self
            .style
            .charset
            .horizontal
            .encode_utf8(&mut buf)
            .as_bytes();
        for _ in 0..self.style.gutter_width {
            self.writer.write_all(gutter_bytes)?;
        }
        Ok(())
    }

    #[inline]
    fn style(&self) -> &Style {
        &self.style
    }

    #[inline]
    fn write_annotation(&mut self, line: &str) -> io::Result<()> {
        self.writer.write_all(line.as_bytes())
    }

    #[inline]
    fn write_newline(&mut self) -> io::Result<()> {
        self.writer.write_all(b"\n")
    }
}

impl<W: io::Write> io::Write for IOWriter<W> {
    #[inline]
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.writer.write(buf)
    }

    #[inline]
    fn flush(&mut self) -> io::Result<()> {
        self.writer.flush()
    }

    #[inline]
    fn write_vectored(&mut self, bufs: &[io::IoSlice<'_>]) -> io::Result<usize> {
        self.writer.write_vectored(bufs)
    }

    #[inline]
    fn write_all(&mut self, buf: &[u8]) -> io::Result<()> {
        self.writer.write_all(buf)
    }

    #[inline]
    fn write_fmt(&mut self, args: fmt::Arguments<'_>) -> io::Result<()> {
        self.writer.write_fmt(args)
    }
}

impl<W: io::Write> DiagramWrite for IOWriter<W> {
    type Error = io::Error;

    #[inline]
    fn write_fmt(&mut self, args: fmt::Arguments<'_>) -> Result<(), Self::Error> {
        Shim(self).write_fmt(args)
    }

    #[inline]
    fn write_branch(
        &mut self,
        start: usize,
        skip: usize,
        branch: Branch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_branch(start, skip, branch)
    }

    #[inline]
    fn write_merge_branch(
        &mut self,
        start: usize,
        skip: usize,
        merge: MergeBranch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_merge_branch(start, skip, merge)
    }

    #[inline]
    fn prepare_annotation(
        &mut self,
        _idx: usize,
        written: usize,
        required: usize,
    ) -> Result<(), Self::Error> {
        Shim(self).prepare_annotation(written, required)
    }

    #[inline]
    fn write_annotation(&mut self, _idx: usize, line: &str) -> Result<(), Self::Error> {
        Shim(self).write_annotation(line)
    }

    #[inline]
    fn write_newline(&mut self) -> Result<(), Self::Error> {
        Shim(self).write_newline()
    }
}

/// A diagram writer which writes into a [`fmt::Write`] implementation.
///
/// Often, this is a wrapper around a string buffer.
pub struct FmtWriter<W> {
    /// The style.
    style: Style,
    /// The writer.
    writer: W,
}

impl<W> FmtWriter<W> {
    /// Construct a new diagram writer with the provided style and internal [`fmt::Write`]
    /// implementation.
    ///
    /// Also see the [`Style::fmt_writer`] method.
    #[inline]
    pub const fn new(style: Style, writer: W) -> Self
    where
        W: fmt::Write,
    {
        Self { style, writer }
    }

    /// Get a mutable reference to the internal writer.
    ///
    /// Note that this struct automatically implements [`fmt::Write`] by passing writes to
    /// the internal writer.
    #[inline]
    pub const fn writer(&mut self) -> &mut W {
        &mut self.writer
    }

    /// Get a reference to the internal style.
    ///
    /// If you must modify the style, first decompose into [components](Self::components) and then rebuild
    /// this struct.
    #[inline]
    pub const fn style(&self) -> &Style {
        &self.style
    }

    /// Recover the style and the internal writer.
    #[inline]
    pub fn components(self) -> (Style, W) {
        (self.style, self.writer)
    }
}

impl<W: fmt::Write> WriteInner for FmtWriter<W> {
    type Error = fmt::Error;

    #[inline]
    fn write_fmt(&mut self, args: std::fmt::Arguments<'_>) -> Result<(), Self::Error> {
        self.writer.write_fmt(args)
    }

    #[inline]
    fn write_char(&mut self, ch: char) -> fmt::Result {
        self.writer.write_char(ch)
    }

    #[inline]
    fn write_gutter(&mut self) -> fmt::Result {
        for _ in 0..self.style.gutter_width {
            self.writer.write_char(self.style.charset.horizontal)?;
        }
        Ok(())
    }

    #[inline]
    fn style(&self) -> &Style {
        &self.style
    }

    #[inline]
    fn write_annotation(&mut self, line: &str) -> fmt::Result {
        self.writer.write_str(line)
    }

    #[inline]
    fn write_newline(&mut self) -> fmt::Result {
        self.writer.write_char('\n')
    }
}

impl<W: fmt::Write> DiagramWrite for FmtWriter<W> {
    type Error = fmt::Error;

    #[inline]
    fn write_fmt(&mut self, args: std::fmt::Arguments<'_>) -> Result<(), Self::Error> {
        self.writer.write_fmt(args)
    }

    #[inline]
    fn write_branch(
        &mut self,
        start: usize,
        skip: usize,
        branch: Branch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_branch(start, skip, branch)
    }

    #[inline]
    fn write_merge_branch(
        &mut self,
        start: usize,
        skip: usize,
        merge: MergeBranch,
    ) -> Result<(), Self::Error> {
        Shim(self).write_merge_branch(start, skip, merge)
    }

    #[inline]
    fn prepare_annotation(
        &mut self,
        _idx: usize,
        written: usize,
        required: usize,
    ) -> Result<(), Self::Error> {
        Shim(self).prepare_annotation(written, required)
    }

    #[inline]
    fn write_annotation(&mut self, _idx: usize, line: &str) -> Result<(), Self::Error> {
        Shim(self).write_annotation(line)
    }

    #[inline]
    fn write_newline(&mut self) -> Result<(), Self::Error> {
        Shim(self).write_newline()
    }
}

impl<W: fmt::Write> fmt::Write for FmtWriter<W> {
    #[inline]
    fn write_str(&mut self, s: &str) -> fmt::Result {
        self.writer.write_str(s)
    }

    #[inline]
    fn write_char(&mut self, c: char) -> fmt::Result {
        self.writer.write_char(c)
    }

    #[inline]
    fn write_fmt(&mut self, args: fmt::Arguments<'_>) -> fmt::Result {
        self.writer.write_fmt(args)
    }
}
